name: drupal-admin-ui
recipe: drupal8
config:
  php: 7.2
  via: nginx
  # via: apache
  webroot: ./demo/docroot
  database: mariadb
  xdebug: true

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'http://drupal-admin-ui.lndo.site'
        SIMPLETEST_BASE_URL: 'http://drupal-admin-ui.lndo.site'
        PHP_IDE_CONFIG: 'serverName=http://drupal-admin-ui.lndo.site'
        SYMFONY_DEPRECATIONS_HELPER: 'disabled'
  database:
    type: mariadb
    creds:
      user: drupal
      password: drupal
      database: drupal
  node:
    type: node
    globals:
      yarn: "1.15.0"
    port: 3000
    overrides:
      environment:
        REACT_APP_DRUPAL_BASE_URL: 'http://drupal-admin-ui.lndo.site'
        NIGHTWATCH_LOGIN_admin_PASSWORD: 'admin'
    build:
      - yarn install

events:
  post-start:
    # lando-setup run only if settings.php is not created on sites/default
    # at this point all the services are running.
    - cd /app/demo && /bin/sh /app/demo/lando-setup.sh

tooling:
  admin-ui-start:
    service: node
    description: run the admin ui
    cmd:
      - yarn install
      - yarn workspace @drupal/admin-ui start
  yarn:
    service: node
    description: run yarn commands
  npm:
    service: node
  node:
    service: node
